{
 "title": "Smart Meter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Consumtion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  Pch,\n  Pcl\nFROM FluviusMeter\nWHERE\n  $__timeFilter(reading_time)\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Power Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  Pph,\n  Ppl\nFROM FluviusMeter\nWHERE\n  $__timeFilter(reading_time)\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Total Power P/C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  Pc,\n  Pp\nFROM FluviusMeter\nWHERE\n  $__timeFilter(reading_time)\nORDER BY reading_time"
    }
   ]
  },
  { "title": "Liquids", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Water",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "areaM2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  Vw\nFROM FluviusMeter\nWHERE\n  $__timeFilter(reading_time) AND\n  Vw != -1\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "areaM2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  Vg\nFROM FluviusMeter\nWHERE\n  $__timeFilter(reading_time) AND\n  Vg != -1\nORDER BY reading_time"
    }
   ]
  },
  { "title": "Extras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  UL1,\n  UL2,\n  UL3\nFROM FluviusMeter\nWHERE\n  $__timeFilter(reading_time)\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  IL1,\n  IL2,\n  IL3\nFROM FluviusMeter\nWHERE\n  $__timeFilter(reading_time)\nORDER BY reading_time"
    }
   ]
  }
 ]
}